language: node_js
node_js:
  - '5'

install:
  - npm install

script:
  - npm run lint
  - gulp build
  - npm test

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  - provider: s3
    access_key_id: AKIAITF53XKH62K4352A
    secret_access_key: &1
      secure: SlovD8rI+ze5JgewH4QFmcufQp05fxcUiXmyES30VFHnyEXhTt403W4nsjVx4ED6KM1l1OlAdiaTWHnR7yod+dDDjRdnn9rYZWdP/iFqGttwZF1TQYh0A0JfxGYLYPGXQZn/xL5jwO2STncy2sU3s9UnREZdb1hdJE+ThmB071bbp02gS0bOm8WZi10LyZ6CBlQyTk9MlvH9SUhay9+5V4anpXmvaij2oedwTEhVRqYCh4gnznFKpoTf6oK+OseioI0JSfgcCKM92c4AebmNt18cr4iziqR+4YU840x4tMiNA3lyscqjiGbwIWIDmb8qxzvN8OSk6SeOrZvm/6TFO79k1jpZvggYYKs5Zj+z8xDLlWEeGvDila1eJl5DNVjdwI9h2U1TWnspJmL2xAGgMR12ByyqAiXRPvuxBbaHDoYM2iEMDxl8gWgvAI/yQjosThOL7aDMQfmJV+63cCNBkc2WC5FX83/SzEiyFYcnWckVUPetfw4MZ9YuCAY3rqrNZ9Z371rcYVUja5FfKcI2pz1XrPnm+9i5U8SPsAXoe6lL7dkZUhTlh0qWa83huGMOMLw8mbjL5mgTztyK8nmzokLiNoPLlntlfdX5WOjLKKCbrewcP5LNhg23avX/KPOgJPz9+VgE7Nzo4ewpZ48u+uRUvTjY+E/qlyZA958k6N8=
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: city-stories/city-stories
    bucket: city-stories-codedeploy
  - provider: codedeploy
    access_key_id: AKIAITF53XKH62K4352A
    secret_access_key: *1
    bucket: city-stories-codedeploy
    key: latest.zip
    bundle_type: zip
    application: CityStories
    deployment_group: DemoFleet
    on: *2
